Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  config.vm.network :private_network, ip: "192.168.33.16"
  config.vm.synced_folder "../../CB203/", "/opt/sites/CB203", owner: "root",
  group: "root", mount_options: ['dmode=777,fmode=777']
end

Vagrant::Config.run do |config|
  config.vm.box = "ubuntu-server-12042-x64-vbox4210.box"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"

  config.vm.host_name = "mybox"

  # Requires hosts updater plugin `vagrant plugin install vagrant-hostsupdater`
  config.hostsupdater.aliases = ["CB203.local"]

  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe "java"
    chef.add_recipe "git"
    chef.add_recipe "vim"
    chef.add_recipe "nginx"
    chef.add_recipe "mysql"
    chef.add_recipe "mysql::server"

    chef.json = {

      "mysql" => {
        "server_root_password" => "myboxadmin",
        "server_repl_password" => "myboxadmin",
        "server_debian_password" => "myboxadmin",
        "bind_address" => "0.0.0.0"
      }

    }

    config.vm.provision :shell, :path => "install.sh"
  end

end

# 1) Install Vagrant
# 2) Install VirtualBox
# 4) Install Git
# 6) Clone repo git clone {pathtorepo}
# 7) cd to repo path on local
# 8) Edit Vagrant file to point sync folder to spot on your local machine where your code lives
# 10) run vagrant up
# 11) develop away