---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
    customize:
      memory: 1024
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      memory: 1024
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
    customize:
      memory: 1024
  run_list:
  - recipe[apt]

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    customize:
      memory: 1024

- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
    customize:
      memory: 1024

suites:
- name: server-community
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::server]
  attributes:
    couchbase:
      server:
        password: "whatever"

- name: server-enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::server]
  attributes:
    couchbase:
      server:
        edition: "enterprise"
        password: "whatever"
        version: "2.1.0"

- name: moxi
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::moxi]
  attributes: {}

- name: client
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::client]
  attributes: {}
